AlignArray:
  Enabled: false
Documentation:
  Enabled: false
EmptyLines:
  Enabled: false
HashSyntax:
  Enabled: true
IfUnlessModifier:
  Enabled: false
LeadingCommentSpace:
  Enabled: false
LineLength:
  Enabled: false
IndentationWidth:
  Enabled: false
MethodCallParentheses:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
StringLiterals:
  Enabled: false
TrailingBlankLines:
  Enabled: false
TrailingComma:
  Enabled: false
